---
title: "Input data format"
author: "XiChen"
date:  "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,results = "axis",eval = T,warning=FALSE,message=FALSE)
```

 
> SPARKLE supports multiple input formats. Users can directly input single-cell Seurat objects,Seurat metadata, or dataframes with calculated cell proportions.


# Input formats 1: Seurat objects

```{r}


library(SPARKLE)

seurat_object <-MNP.seurat_object
class(seurat_object)

sparkle.data <- cwas_build_model_data(inputdata = seurat_object,Sample = "Patient.No",Phenotype = "Status",Celltype ="Clusters",Group ="Tissue",Subgroup = "Study.No",Control_label = "Healthy",Disease_label = "Cancer")  

```

# Input formats 2: Seurat metadata

```{r}

metadata <-MNP.metadata 
knitr::kable(head(metadata), caption = "Seurat metadata") 
sparkle.data <- cwas_build_model_data(inputdata = metadata,Sample = "Patient.No",Phenotype = "Status",Celltype ="Clusters",Group ="Tissue",Subgroup = "Study.No",Control_label = "Healthy",Disease_label = "Cancer")
 

```

# Input formats 3: data frame with cell rate information

```{r}

 

covid.data.ratio <-SPARKLE::covid.data 

knitr::kable(head(covid.data.ratio) , caption = "Cell rate information table") 
sparkle.data <- cwas_build_model_data(inputdata = covid.data.ratio,Sample = "sampleID",Phenotype = "severity",Celltype ="celltype",Group ="tissue",Subgroup = "dataset",Control_label = "control",Disease_label = "severe/critical",Cellrate ="cellratio" )

```
